<div class="container"> 
        <h2>Registre-se com esse formulário!</h2><br><br>

        <?php echo $this->tag->form("tutorial/signup/register"); ?>

            <p>
                <label for="name">Nome: </label>
                <?php echo $this->tag->textField("name"); ?>
            </p>

            <p>
                <label for="email">E-Mail: </label>
                <?php echo $this->tag->textField("email"); ?>
            </p>
            <br>
            <p>
                <?php echo $this->tag->submitButton(["Registrar",'class' => 'btn btn-primary']); ?>
            </p>

        </form>
</div> 