<?php

echo PHP_EOL;

echo PHP_EOL;

echo "<h1>Olá Mundo!</h1><br><br>";

//botão de registro linkado ao singup index

echo $this->tag->linkTo(["tutorial/signup", "Registre-se aqui!", 'class' => 'btn btn-primary']);

if ($users->count() > 0) {
    ?>
    <br><br>
    <table class="table table-bordered table-hover">
        <thead class="thead-light">
        <tr>
            <th>ID</th>
            <th>Nome</th>
            <th>E-mail</th>
        </tr>
        </thead>
        <tfoot>
        <tr>
            <td colspan="3">Quantidade de usuários: <?php echo $users->count(); ?></td>
        </tr>
        </tfoot>
        <tbody>
        <?php foreach ($users as $user) { ?>
            <tr>
                <td><?php echo $user->id; ?></td>
                <td><?php echo $user->name; ?></td>
                <td><?php echo $user->email; ?></td>
            </tr>
        <?php } ?>
        </tbody>
    </table>
    <?php
}

?>